### ISSUE TITLE
Some questions about tls_cameraDPAF.mlx

### ISSUE THREAD

**Issue by zhihaofan** [Zhenyi-Liu/iset3d-v4#1]
I am trying to run this script, but I have encountered some problems. I made an error when rendering PBRT in the place of "Show Just the Imaging lens" , showing "Omni: Camera Type Unknown". May I ask how to solve this problem?
In addition, I had the same problem with rendering this script separately in Docker. After adding the camera parameters

Local Environment:
Ubuntu: 16.0.4
Docker: 20.10.7
image: camerasimulation/pbrt-v4-cpu
Matlab : 2021b

![image](https://user-images.githubusercontent.com/59326288/193272199-df663463-922f-4e15-b57c-547aac09ea10.png)

**Comment by zhihaofan** [comment]
I check the code of pbrt in image and there is no description of the class of 'OmniCamera'. Is it because I downloaded the wrong image? The original image is run from the 'docker pull camerasimulation/pbrt-v4-cpu' command.

**Comment by Zhenyi-Liu** [comment]
Sorry for the late reply, you can try with this image: digitalprodev/pbrt-v4-cpu

**Comment by zhihaofan** [comment]
> Sorry for the late reply, you can try with this image: digitalprodev/pbrt-v4-cpu

Thank you very much. It worked.
